abstract class AppState{}
class InitialState extends AppState{}
class LoginPasswordState extends AppState{}
class RadioButtonState extends AppState{}
class CheckBoxHomeState extends AppState{}
class CheckBoxWorkState extends AppState{}
class SignUpPassword1State extends AppState{}
class SignUpPassword2State extends AppState{}
class ForgetPassword1State extends AppState{}
class ForgetPassword2State extends AppState{}
class ChangeIndexBottomNavBarState extends AppState{}
class CarouselState extends AppState{}
class Carousel2State extends AppState{}
class Container1State extends AppState{}
class Container2State extends AppState{}
class Container3State extends AppState{}
class Container4State extends AppState{}
class Container5State extends AppState{}
class Container1_16State extends AppState{}
class Container2_16State extends AppState{}
class Container3_16State extends AppState{}
class Container4_16State extends AppState{}
class Container5_16State extends AppState{}
class OrderTools1State extends AppState{}
class OrderTools2State extends AppState{}
class OrderTools3State extends AppState{}
class OtherToolsState extends AppState{}
class AmountPlusState extends AppState{}
class AmountMinusState extends AppState{}
class SaveAddressState extends AppState{}
class NumScreen58State extends AppState{}
class LangugeState extends AppState{}
class ControllerContryState extends AppState{}
class UnderLineColor110State extends AppState{}
class UnderLineColor111_1State extends AppState{}
class UnderLineColor111_2State extends AppState{}
class NumberBody130State extends AppState{}
class Counter116130State extends AppState{}
class Counter119_1State extends AppState{}
class Price119_1State extends AppState{}
class RsomTarkeb119_1State extends AppState{}
class RsomTawsel119_1State extends AppState{}
class Total119_1State extends AppState{}
class Price119_2State extends AppState{}
class RsomTawsel119_2State extends AppState{}
class Total119_2State extends AppState{}
class Counter119_2State extends AppState{}
class BodyNumber116State extends AppState{}